# Generated by Django 6.0.2 on 2026-02-14 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], default='OUT', max_length=3, verbose_name='Tipo')),
                ('category', models.CharField(choices=[('ALM', 'Alimentação'), ('TRP', 'Transporte'), ('MOR', 'Moradia'), ('SAU', 'Saúde'), ('EDU', 'Educação'), ('LAZ', 'Lazer'), ('COM', 'Compras'), ('SAL', 'Salário'), ('INV', 'Investimento'), ('OUT', 'Outros')], default='OUT', max_length=3, verbose_name='Categoria')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluída')),
                ('date', models.DateField(verbose_name='Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
